import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import gshai from '../components/Ginny.png';
import { useState } from "react";
export default function Home() {
  const[darkMode,setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode? "dark":""}  >
      
    <Head >
      <title>Ginny Shai</title>
      <meta  name="description" content="Generated by "/>
      <link rel="icon" href="/favicon.ico" />
    </Head>
    

    <main className="bg-white  dark:bg-gray-900 dark:text-white md:px-12 md:mt-2 ">
      <section className="min-h-screen">
      <nav className="p-8 mb-12 flex justify-between ">
      <h1 className="text-[23px]  font-Stylish font-medium lg:text-[43px]  ">Ginny Shai</h1>
      <ul className="flex items-center justify-around">
        <li>
          <BsFillMoonStarsFill className="cursor-pointer" onClick={()=>setDarkMode(!darkMode)}/></li>
        <li>
          <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 ml-7 px-4 py-2 rounded-md ">Resume</a>
          </li>
      </ul>
    </nav>
    <div className="text-center p-10 py-10">
      <h2 className="text-5xl py-2 text-teal-600 font-medium">Ginny Shai</h2>
      <h3 className="text-2xl py-2">Python Developer and Technical Writer</h3>
    <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">Freelancer providing services for programming and for projects needs.Join me down below and let's get cracking </p>
    </div>
    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
      <a href="https://twitter.com/Beingginnyshai" className="">

            <AiFillTwitterCircle className="hover:ease-in-out duration-300 hover:scale-[1.3] hover:text-[#1d9bf0]" />
      </a>
      <a href="https://www.linkedin.com/in/ginny-shai-543761232">


      <AiFillLinkedin className="hover:ease-in-out duration-300 hover:scale-[1.3] hover:text-[#0a66c2]"/>
</a>
<a href="https://youtube.com/@hellodotpy" >

<AiFillYoutube className="hover:ease-in-out duration-300 hover:scale-[1.3] hover:text-[#ff0000]"/>

</a>
    
    </div>
     <div className="realtive bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-14 mx-auto overflow-hidden">
       <Image  src={gshai} alt='Ginny Standing Front'  />
     </div>
      </section>
      <section>
        <div className="p-8">
      <h3 className="text-2xl "><span className="border-4 border-transparent border-b-teal-500
">Python</span>Dev🐍</h3>
      <p className="text-md py-2 leading-8 text-gray-600">I am a Python developer and I am currently learning Python. I have been working with <span className="text-teal-500">Python</span> for a while now, but I am always looking to improve my <span className="text-teal-500">skills</span> and stay up-to-date with the latest developments in the language.</p>
      <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">I am from Dharamshala, Himachal Pradesh and I have a great passion for artificial intelligence. I have always been fascinated by the potential of AI to transform the world and improve people's lives, and I am excited to learn more about this rapidly-evolving field.  </p>
        </div>
        <div>
          <div>

          </div>
        </div>
      </section>
    </main>
    </div>
   
    </>
  )
}
